### PR TITLE
Eventually refactoring and minor fixes

### LINKED ISSUE #120: Refactoring e2e test suite
It appears, from time to time, we got flaky tests as happened [here](https://github.com/clastix/capsule/pull/118/checks?check_run_id=1335492495): in this case, is not definitely an issue of an underlying Capsule error, but rather the respawn of the Capsule pod not so quick to deal with the args changes.

My suggestion is to use the `Eventually` helper also for the resource creations inside the `JustBeforeEach` blocks.

https://github.com/clastix/capsule/blob/ee6e3aa0df79ada668d68f3a174eb09ae2617bc5/e2e/custom_capsule_group_test.go#L52-L55

Last but not least, we could also refactor the test utilities, returning an `AsyncAssertion` rather than a `Should` assertion: this would help also the error reporting since the assertion would be made at the test feature implementation.

### PR DESCRIPTION
**Pull request by prometherion**
Closes #120.

### CODE REVIEW

File: e2e/container_registry_test.go [hunk 1]
```diff
@@ -33,7 +33,7 @@ import (
 var _ = Describe("enforcing a Container Registry", func() {
 	tnt := &v1alpha1.Tenant{
 		ObjectMeta: metav1.ObjectMeta{
-			Name: "additional-role-binding",
+			Name: "container-registry",
```
Comment (prometherion) [inline e2e/container_registry_test.go:36]: Just a typo in the Tenant name, not so critical.

File: e2e/container_registry_test.go [hunk 2]
```diff
@@ -44,51 +44,35 @@ var _ = Describe("enforcing a Container Registry", func() {
...
 	It("should add labels to Namespace", func() {
 		ns := NewNamespace("registry-labels")
 		NamespaceCreation(ns, tnt, defaultTimeoutInterval).Should(Succeed())
-
-		Eventually(func() bool {
-			if err := k8sClient.Get(context.Background(), types.NamespacedName{Name: ns.Name}, ns); err != nil {
-				return false
+		Eventually(func() (ok bool) {
+			Expect(k8sClient.Get(context.Background(), types.NamespacedName{Name: ns.Name}, ns)).Should(Succeed())
+			ok, _ = HaveKeyWithValue("capsule.clastix.io/allowed-registries", "docker.io,docker.tld").Match(ns.Annotations)
```
Comment (prometherion) [inline e2e/container_registry_test.go:64]: Although is an upside-down assertion, this works well since we don't know when the Namespace has been totally processed by the controller.

File: e2e/resource_quota_exceeded_test.go [hunk 3]
```diff
@@ -166,63 +165,41 @@ var _ = Describe("exceeding Tenant resource quota", func() {
 				}
 				_, err = cs.AppsV1().Deployments(namespace).Create(context.TODO(), d, metav1.CreateOptions{})
 				return
-			}, 15*time.Second, time.Second).Should(Succeed())
```
Comment (prometherion) [inline e2e/resource_quota_exceeded_test.go:169]: This is legacy hard-coded time values.

File: e2e/resource_quota_exceeded_test.go [hunk 4]
```diff
@@ -166,63 +165,41 @@ var _ = Describe("exceeding Tenant resource quota", func() {
...
 			By("ensuring the status has been blocked with actual usage", func() {
 				Eventually(func() corev1.ResourceList {
 					_ = k8sClient.Get(context.TODO(), types.NamespacedName{Name: n, Namespace: ns}, rq)
 					return rq.Status.Hard
-				}, 15*time.Second, time.Second).Should(Equal(rq.Status.Used))
+				}, defaultTimeoutInterval, defaultPollInterval).Should(Equal(rq.Status.Used))
 			})
 			By("creating an exceeded Pod", func() {
-				d := &v1.Deployment{
+				pod := &corev1.Pod{
```
Comment (prometherion) [inline e2e/resource_quota_exceeded_test.go:185]: Rather than creating Deployment, checking ReplicaSet and finally conditions, is it more suitable to run a single Pod!

File: e2e/service_metadata_test.go [hunk 5]
```diff
@@ -51,49 +54,40 @@ var _ = Describe("creating a Service/Endpoint/EndpointSlice for a Tenant with ad
 					"clastix.io/custom-annotation": "buzz",
 				},
 			},
-		},
-	}
-	epsCR := &rbacv1.ClusterRole{
```
Comment (prometherion) [inline e2e/service_metadata_test.go:56]: Taking advantage of the additional role bindings offered with latest versions of Capsule, using the `endpointslice-controller`.
