### PR TITLE
fix: object count resource quotas not working when using Tenant scope

### LINKED ISSUE #507: object count resource quotas not working when using Tenant scope
Create a tenant with the following spec:

```yaml
kubectl apply -f - << EOF
apiVersion: capsule.clastix.io/v1beta1
kind: Tenant
metadata:
  name: oil
spec:
  owners:
  - name: alice
    kind: User
  namespaceOptions:
    quota: 3
  resourceQuotas:
    scope: Tenant
    items:
    - hard:
        count/jobs.batch: "10"
EOF
```

as tenant owner create a namespace
```
 kubectl --kubeconfig=alice-oil.kubeconfig create ns oil-foo
```

following errors will appear in capsule controller logs:
```
{"level":"error","ts":"2022-01-25T13:26:50.559Z","logger":"controllers.Tenant","msg":"Cannot sync ResourceQuota items","Request.Name":"oil","error":"update of outer ResourceQuota items has failed: ResourceQuota \"capsule-oil-0\" is invalid: [metadata.annotations: Invalid value: \"quota.capsule.clastix.io/hard-count/jobs.batch\": a qualified name must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]') with an optional DNS subdomain prefix and '/' (e.g. 'example.com/MyName'), metadata.annotations: Invalid value: \"quota.capsule.clastix.io/used-count/jobs.batch\": a qualified name must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]') with an optional DNS subdomain prefix and '/' (e.g. 'example.com/MyName')]","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.5/pkg/internal/controller/controller.go:298\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.5/pkg/internal/controller/controller.go:253\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.5/pkg/internal/controller/controller.go:214"}
{"level":"error","ts":"2022-01-25T13:26:50.561Z","logger":"controller-runtime.manager.controller.tenant","msg":"Reconciler error","reconciler group":"capsule.clastix.io","reconciler kind":"Tenant","name":"oil","namespace":"","error":"update of outer ResourceQuota items has failed: ResourceQuota \"capsule-oil-0\" is invalid: [metadata.annotations: Invalid value: \"quota.capsule.clastix.io/hard-count/jobs.batch\": a qualified name must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]') with an optional DNS subdomain prefix and '/' (e.g. 'example.com/MyName'), metadata.annotations: Invalid value: \"quota.capsule.clastix.io/used-count/jobs.batch\": a qualified name must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]') with an optional DNS subdomain prefix and '/' (e.g. 'example.com/MyName')]","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.5/pkg/internal/controller/controller.go:253\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.5/pkg/internal/controller/controller.go:214"}
```

empty `ResourceQuota` will be created in `oil-foo` namespace
```yaml
kubectl get resourcequotas -n oil-foo capsule-oil-0 -oyaml
apiVersion: v1
kind: ResourceQuota
metadata:
  creationTimestamp: "2022-01-25T13:26:49Z"
  labels:
    capsule.clastix.io/resource-quota: "0"
    capsule.clastix.io/tenant: oil
  name: capsule-oil-0
  namespace: oil-foo
  ownerReferences:
  - apiVersion: capsule.clastix.io/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: Tenant
    name: oil
    uid: c46d9ec1-6141-4a01-b957-8d71f19b0f66
  resourceVersion: "2296"
  selfLink: /api/v1/namespaces/oil-foo/resourcequotas/capsule-oil-0
  uid: 583ffa15-485c-4ad4-a7dd-a57cabe22f77
spec: {}
status: {}

```

### PR DESCRIPTION
**Pull request by MaxFedotov**
closes #507

### CODE REVIEW

File: controllers/tenant/resourcequotas.go [hunk 1]
```diff
@@ -211,6 +212,9 @@ func (r *Manager) syncResourceQuota(tenant *capsulev1beta1.Tenant, namespace str
 func (r *Manager) resourceQuotasUpdate(resourceName corev1.ResourceName, actual, limit resource.Quantity, list ...corev1.ResourceQuota) (err error) {
 	group := new(errgroup.Group)
 
+	// Handle object count quotas (https://kubernetes.io/docs/concepts/policy/resource-quotas/#object-count-quota). As / symbol is not allowed in annotations, replace it to _
+	resourceName = corev1.ResourceName(strings.ReplaceAll(resourceName.String(), "/", "_"))
+
```
Comment (prometherion) [inline controllers/tenant/resourcequotas.go:217]: Can we move this logic to the file `tenant_annotations.go`?

**Review by prometherion — CHANGES_REQUESTED** [review]

**Review by prometherion — APPROVED** [review]
